### ISSUE TITLE
Method getPackageInfo() returns null applicationInfo property

### ISSUE THREAD

**Issue by pablo8899** [nsNeruno/android_package_manager#1]
Hi im using your plugin to get ApplicationInfo of application.
It's really great plugin and thank you for sharing it.
However i found one issue  with method getPackageInfo().
Method always return null property aplicationInfo.
I was looking into code and i found one problem code:

data['applicationInfo'] is Map<String, dynamic> always returns false even if Map is filled with data

![image](https://user-images.githubusercontent.com/37773477/195382939-7f6d5b43-d3be-4f35-ae85-7e8c944c09ca.png)

i changed it to :
![image](https://user-images.githubusercontent.com/37773477/195383408-93211054-68bb-4866-aa9d-ebe4ec6b01e2.png)

and it works now.

Sorry for my bad english and i hope attached code will help solve problem.

**Comment by nananSoluix** [comment]
Hi @pablo8899, thanks for pointing out the problem
I've published an [update](https://github.com/nsNeruno/android_package_manager/commit/aa22b65386506b5be95b5689e96b1d0e4bac333b) for it, updated the tests.
Sorry for the late reply

**Comment by nsNeruno** [comment]
Hi @pablo8899, thanks for pointing out the problem
I've published an [update](https://github.com/nsNeruno/android_package_manager/commit/aa22b65386506b5be95b5689e96b1d0e4bac333b) for it, updated the tests.
Sorry for the late reply
