### ISSUE TITLE
No Way to Get a Package's Version Code

### ISSUE THREAD

**Issue by ImranR98** [nsNeruno/android_package_manager#10]
Neither the [`getLongVersionCode()`](https://developer.android.com/reference/android/content/pm/PackageInfo#getLongVersionCode()) function nor the deprecated [`versionCode`](https://developer.android.com/reference/android/content/pm/PackageInfo#versionCode) property of `PackageInfo` are available from the Flutter side.

**Comment by nsNeruno** [comment]
Added `longVersionCode` property to `PackageInfo` on `v0.7.0`
