### ISSUE TITLE
Can't see permission list

### ISSUE THREAD

**Issue by EvilWatermelon** [nsNeruno/android_package_manager#12]
I'm trying to get the permissions of my installed apps but can't see them. 

```
List<PermissionInfo> permissionList = [];
    final pm = AndroidPackageManager();
    pm.getPackageInfo(packageName: package).then(
      (value) => {
          print("Permissions: $value.permissions"),
          if (value.permissions != null) { 
            permissionList = value.permissions!,
          } else {
            const Text('No permissions')
          }
      },
    );
```
The output shows only `Permissions: Instance of 'PackageInfoImpl'.permissions`.
And the if condition only jumps into the else condition even if there are permissions.

**Comment by nsNeruno** [comment]
Additional note,
I published `v0.7.0`. Please give it a try
