### ISSUE TITLE
`getInstallSourceInfo` and `getInstallerPackageName` Unavailable

### ISSUE THREAD

**Issue by ImranR98** [nsNeruno/android_package_manager#9]
The code for `getInstallSourceInfo` (for SDK >= R) is [already there](https://github.com/nsNeruno/android_package_manager/blob/e97b52d7fc8fecf8b731873d6eb0bb0ee432263d/android/src/main/kotlin/lab/neruno/android_package_manager/AndroidPackageManagerPlugin.kt#L652) but not exposed by the `AndroidPackageManagerImpl` class.

[`getInstallerPackageName`](https://developer.android.com/reference/android/content/pm/PackageManager#getInstallerPackageName(java.lang.String)) (for SDK < R) is also not available.

**Comment by nsNeruno** [comment]
Added on [#6fac438](https://github.com/nsNeruno/android_package_manager/commit/6fac438b6c643f203963c875d918732223700c4b).

Added specific [Integration tests](https://github.com/nsNeruno/android_package_manager/blob/master/example/integration_test/install_source_test.dart) for this

**Comment by ImranR98** [comment]
Thank you! Just fyi looks like the latest stable version of Flutter uses Dart SDK 3.0.6 so running `flutter pub add android_download_manager` gives you `0.5.0` since `0.5.4` only works with Dart `<3.0.0`. I manually changed this to `<4.0.0` in a fork and it seems to work fine.
